name: aMule
slug: amule
description: aMule P2P client
version: "1.0.0"
arch:
  - amd64
  - armv7
  - arm64
startup: services
boot: auto
ports:
  4711/tcp: 4711
  4712/tcp: 4712
  4662/tcp: 4662
  4665/udp: 4665
  4672/udp: 4672
options: {}
schema: {}
