name: aMule
version: "1.0.0"
slug: amule
description: aMule P2P client
url: "https://github.com/GazKez/Gazlaxy-s-Addons/tree/main/amule"
arch:
  - amd64
  - armv7
  - arm64
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/home-assistant/{arch}-addon-example"
