name: "aMule"
description: "Cliente eMule para Home Assistant"
version: "1.0.0"
slug: "amule_addon"
arch:
  - amd64
ports:
  4711/tcp: 4711 # Interfaz Web
  4662/tcp: 4662 # Puerto eMule
  4672/udp: 4672 # Puerto eMule
map:
  - config:rw # Para que los datos no se borren al reiniciar
  - share:rw  # Para guardar las descargas en la carpeta share de HA
options:
  puid: 1000
  pgid: 1000
  tz: "Europe/Madrid"
  webui_pwd: "admin"
  mod_auto_restart_enabled: true
schema:
  puid: int
  pgid: int
  tz: str
  gui_pwd: password?
  webui_pwd: password
  mod_auto_restart_enabled: bool
  mod_auto_restart_cron: str?
  mod_auto_share_directories: str?
